apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"web"},"name":"web","namespace":"default"},"spec":{"ports":[{"name":"web-traffic","port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"web"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2022-01-19T13:31:47Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "37398"
  selfLink: /api/v1/namespaces/default/services/web
  uid: 564700c9-a531-46fa-ae2e-155070177591
spec:
  clusterIP: 10.0.142.127
  externalTrafficPolicy: Cluster
  ports:
  - name: web-traffic
    nodePort: 32752
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 40.87.8.16
